/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.ops.tables.records;


import fr.suivons.db.jooq.ops.tables.IngestionRun;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Exécutions des ingestions (pipeline SPEC §7.3), une ligne par run
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IngestionRunRecord extends UpdatableRecordImpl<IngestionRunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ops.ingestion_run.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ops.ingestion_run.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ops.ingestion_run.source_code</code>.
     */
    public void setSourceCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ops.ingestion_run.source_code</code>.
     */
    public String getSourceCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ops.ingestion_run.version_source</code>.
     */
    public void setVersionSource(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ops.ingestion_run.version_source</code>.
     */
    public String getVersionSource() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ops.ingestion_run.debut</code>.
     */
    public void setDebut(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>ops.ingestion_run.debut</code>.
     */
    public OffsetDateTime getDebut() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>ops.ingestion_run.fin</code>.
     */
    public void setFin(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>ops.ingestion_run.fin</code>.
     */
    public OffsetDateTime getFin() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>ops.ingestion_run.statut</code>.
     */
    public void setStatut(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ops.ingestion_run.statut</code>.
     */
    public String getStatut() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ops.ingestion_run.lus</code>.
     */
    public void setLus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>ops.ingestion_run.lus</code>.
     */
    public Integer getLus() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ops.ingestion_run.charges</code>.
     */
    public void setCharges(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>ops.ingestion_run.charges</code>.
     */
    public Integer getCharges() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>ops.ingestion_run.rejetes</code>.
     */
    public void setRejetes(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>ops.ingestion_run.rejetes</code>.
     */
    public Integer getRejetes() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>ops.ingestion_run.checksum_fichier</code>.
     */
    public void setChecksumFichier(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ops.ingestion_run.checksum_fichier</code>.
     */
    public String getChecksumFichier() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IngestionRunRecord
     */
    public IngestionRunRecord() {
        super(IngestionRun.INGESTION_RUN);
    }

    /**
     * Create a detached, initialised IngestionRunRecord
     */
    public IngestionRunRecord(Long id, String sourceCode, String versionSource, OffsetDateTime debut, OffsetDateTime fin, String statut, Integer lus, Integer charges, Integer rejetes, String checksumFichier) {
        super(IngestionRun.INGESTION_RUN);

        setId(id);
        setSourceCode(sourceCode);
        setVersionSource(versionSource);
        setDebut(debut);
        setFin(fin);
        setStatut(statut);
        setLus(lus);
        setCharges(charges);
        setRejetes(rejetes);
        setChecksumFichier(checksumFichier);
        resetTouchedOnNotNull();
    }
}
