/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.ops.tables.records;


import fr.suivons.db.jooq.ops.tables.Rejet;

import java.time.OffsetDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Enregistrements source rejetés à la transformation, avec leur motif
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RejetRecord extends UpdatableRecordImpl<RejetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ops.rejet.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ops.rejet.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ops.rejet.run_id</code>.
     */
    public void setRunId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ops.rejet.run_id</code>.
     */
    public Long getRunId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ops.rejet.source_record_id</code>.
     */
    public void setSourceRecordId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ops.rejet.source_record_id</code>.
     */
    public String getSourceRecordId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ops.rejet.motif</code>.
     */
    public void setMotif(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ops.rejet.motif</code>.
     */
    public String getMotif() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ops.rejet.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>ops.rejet.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>ops.rejet.cree_le</code>.
     */
    public void setCreeLe(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>ops.rejet.cree_le</code>.
     */
    public OffsetDateTime getCreeLe() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RejetRecord
     */
    public RejetRecord() {
        super(Rejet.REJET);
    }

    /**
     * Create a detached, initialised RejetRecord
     */
    public RejetRecord(Long id, Long runId, String sourceRecordId, String motif, JSONB payload, OffsetDateTime creeLe) {
        super(Rejet.REJET);

        setId(id);
        setRunId(runId);
        setSourceRecordId(sourceRecordId);
        setMotif(motif);
        setPayload(payload);
        setCreeLe(creeLe);
        resetTouchedOnNotNull();
    }
}
