/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.ops.tables.records;


import fr.suivons.db.jooq.ops.tables.Source;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Sources de données (flux et services d'appui), SPEC §4
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SourceRecord extends UpdatableRecordImpl<SourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ops.source.code</code>.
     */
    public void setCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ops.source.code</code>.
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ops.source.libelle</code>.
     */
    public void setLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ops.source.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ops.source.producteur</code>.
     */
    public void setProducteur(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ops.source.producteur</code>.
     */
    public String getProducteur() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ops.source.licence</code>.
     */
    public void setLicence(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ops.source.licence</code>.
     */
    public String getLicence() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ops.source.url_reference</code>.
     */
    public void setUrlReference(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ops.source.url_reference</code>.
     */
    public String getUrlReference() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ops.source.frequence</code>.
     */
    public void setFrequence(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ops.source.frequence</code>.
     */
    public String getFrequence() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourceRecord
     */
    public SourceRecord() {
        super(Source.SOURCE);
    }

    /**
     * Create a detached, initialised SourceRecord
     */
    public SourceRecord(String code, String libelle, String producteur, String licence, String urlReference, String frequence) {
        super(Source.SOURCE);

        setCode(code);
        setLibelle(libelle);
        setProducteur(producteur);
        setLicence(licence);
        setUrlReference(urlReference);
        setFrequence(frequence);
        resetTouchedOnNotNull();
    }
}
