/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.ops;


import fr.suivons.db.jooq.ops.tables.IngestionRun;
import fr.suivons.db.jooq.ops.tables.Rejet;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in ops.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index INGESTION_RUN_SOURCE_DEBUT_IDX = Internal.createIndex(DSL.name("ingestion_run_source_debut_idx"), IngestionRun.INGESTION_RUN, new OrderField[] { IngestionRun.INGESTION_RUN.SOURCE_CODE, IngestionRun.INGESTION_RUN.DEBUT.desc() }, false);
    public static final Index REJET_RUN_IDX = Internal.createIndex(DSL.name("rejet_run_idx"), Rejet.REJET, new OrderField[] { Rejet.REJET.RUN_ID }, false);
}
