/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.ops;


import fr.suivons.db.jooq.ops.tables.IngestionRun;
import fr.suivons.db.jooq.ops.tables.Rejet;
import fr.suivons.db.jooq.ops.tables.Source;
import fr.suivons.db.jooq.ops.tables.records.IngestionRunRecord;
import fr.suivons.db.jooq.ops.tables.records.RejetRecord;
import fr.suivons.db.jooq.ops.tables.records.SourceRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in ops.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<IngestionRunRecord> INGESTION_RUN_PKEY = Internal.createUniqueKey(IngestionRun.INGESTION_RUN, DSL.name("ingestion_run_pkey"), new TableField[] { IngestionRun.INGESTION_RUN.ID }, true);
    public static final UniqueKey<RejetRecord> REJET_PKEY = Internal.createUniqueKey(Rejet.REJET, DSL.name("rejet_pkey"), new TableField[] { Rejet.REJET.ID }, true);
    public static final UniqueKey<SourceRecord> SOURCE_PKEY = Internal.createUniqueKey(Source.SOURCE, DSL.name("source_pkey"), new TableField[] { Source.SOURCE.CODE }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<IngestionRunRecord, SourceRecord> INGESTION_RUN__INGESTION_RUN_SOURCE_CODE_FKEY = Internal.createForeignKey(IngestionRun.INGESTION_RUN, DSL.name("ingestion_run_source_code_fkey"), new TableField[] { IngestionRun.INGESTION_RUN.SOURCE_CODE }, Keys.SOURCE_PKEY, new TableField[] { Source.SOURCE.CODE }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<RejetRecord, IngestionRunRecord> REJET__REJET_RUN_ID_FKEY = Internal.createForeignKey(Rejet.REJET, DSL.name("rejet_run_id_fkey"), new TableField[] { Rejet.REJET.RUN_ID }, Keys.INGESTION_RUN_PKEY, new TableField[] { IngestionRun.INGESTION_RUN.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
