/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.ops;


import fr.suivons.db.jooq.DefaultCatalog;
import fr.suivons.db.jooq.ops.tables.IngestionRun;
import fr.suivons.db.jooq.ops.tables.Rejet;
import fr.suivons.db.jooq.ops.tables.Source;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * Exploitation : sources, exécutions, rejets, signalements
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ops extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ops</code>
     */
    public static final Ops OPS = new Ops();

    /**
     * Exécutions des ingestions (pipeline SPEC §7.3), une ligne par run
     */
    public final IngestionRun INGESTION_RUN = IngestionRun.INGESTION_RUN;

    /**
     * Enregistrements source rejetés à la transformation, avec leur motif
     */
    public final Rejet REJET = Rejet.REJET;

    /**
     * Sources de données (flux et services d'appui), SPEC §4
     */
    public final Source SOURCE = Source.SOURCE;

    /**
     * No further instances allowed
     */
    private Ops() {
        super(DSL.name("ops"), null, DSL.comment("Exploitation : sources, exécutions, rejets, signalements"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            IngestionRun.INGESTION_RUN,
            Rejet.REJET,
            Source.SOURCE
        );
    }
}
