/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.ops;


import fr.suivons.db.jooq.ops.tables.IngestionRun;
import fr.suivons.db.jooq.ops.tables.Rejet;
import fr.suivons.db.jooq.ops.tables.Source;


/**
 * Convenience access to all tables in ops.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Exécutions des ingestions (pipeline SPEC §7.3), une ligne par run
     */
    public static final IngestionRun INGESTION_RUN = IngestionRun.INGESTION_RUN;

    /**
     * Enregistrements source rejetés à la transformation, avec leur motif
     */
    public static final Rejet REJET = Rejet.REJET;

    /**
     * Sources de données (flux et services d'appui), SPEC §4
     */
    public static final Source SOURCE = Source.SOURCE;
}
