/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.raw;


import fr.suivons.db.jooq.ops.tables.IngestionRun;
import fr.suivons.db.jooq.ops.tables.records.IngestionRunRecord;
import fr.suivons.db.jooq.raw.tables.DecpRecord;
import fr.suivons.db.jooq.raw.tables.records.DecpRecordRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in raw.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DecpRecordRecord> DECP_RECORD_PKEY = Internal.createUniqueKey(DecpRecord.DECP_RECORD, DSL.name("decp_record_pkey"), new TableField[] { DecpRecord.DECP_RECORD.SOURCE_RECORD_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DecpRecordRecord, IngestionRunRecord> DECP_RECORD__DECP_RECORD_RUN_ID_FKEY = Internal.createForeignKey(DecpRecord.DECP_RECORD, DSL.name("decp_record_run_id_fkey"), new TableField[] { DecpRecord.DECP_RECORD.RUN_ID }, fr.suivons.db.jooq.ops.Keys.INGESTION_RUN_PKEY, new TableField[] { IngestionRun.INGESTION_RUN.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
