/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.raw;


import fr.suivons.db.jooq.DefaultCatalog;
import fr.suivons.db.jooq.raw.tables.DecpRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * Données brutes telles que reçues, rejouables
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Raw extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>raw</code>
     */
    public static final Raw RAW = new Raw();

    /**
     * DECP : un enregistrement par couple (marché, titulaire), après fusion des
     * lignes du jeu
     */
    public final DecpRecord DECP_RECORD = DecpRecord.DECP_RECORD;

    /**
     * No further instances allowed
     */
    private Raw() {
        super(DSL.name("raw"), null, DSL.comment("Données brutes telles que reçues, rejouables"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DecpRecord.DECP_RECORD
        );
    }
}
