/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.raw;


import fr.suivons.db.jooq.raw.tables.DecpRecord;


/**
 * Convenience access to all tables in raw.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * DECP : un enregistrement par couple (marché, titulaire), après fusion des
     * lignes du jeu
     */
    public static final DecpRecord DECP_RECORD = DecpRecord.DECP_RECORD;
}
