/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core;


import fr.suivons.db.jooq.DefaultCatalog;
import fr.suivons.db.jooq.core.tables.Entreprise;
import fr.suivons.db.jooq.core.tables.Flux;
import fr.suivons.db.jooq.core.tables.Naf;
import fr.suivons.db.jooq.core.tables.Payeur;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * Modèle normalisé : entreprises, payeurs, flux
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Core extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>core</code>
     */
    public static final Core CORE = new Core();

    /**
     * Référentiel minimal des bénéficiaires (ADR 0004) ; identité détaillée lue
     * via l'API Sirene
     */
    public final Entreprise ENTREPRISE = Entreprise.ENTREPRISE;

    /**
     * Flux d'argent public, chacun relié à sa source (provenance obligatoire)
     */
    public final Flux FLUX = Flux.FLUX;

    /**
     * Nomenclature NAF (sous-classes), référentiel public statique
     */
    public final Naf NAF = Naf.NAF;

    /**
     * Organismes payeurs : acheteurs publics, autorités d'octroi, programmes UE
     */
    public final Payeur PAYEUR = Payeur.PAYEUR;

    /**
     * No further instances allowed
     */
    private Core() {
        super(DSL.name("core"), null, DSL.comment("Modèle normalisé : entreprises, payeurs, flux"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Entreprise.ENTREPRISE,
            Flux.FLUX,
            Naf.NAF,
            Payeur.PAYEUR
        );
    }
}
