/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core;


import fr.suivons.db.jooq.core.tables.Flux;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in core.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLUX_BENEFICIAIRE_IDX = Internal.createIndex(DSL.name("flux_beneficiaire_idx"), Flux.FLUX, new OrderField[] { Flux.FLUX.BENEFICIAIRE_SIREN }, false);
    public static final Index FLUX_PAYEUR_IDX = Internal.createIndex(DSL.name("flux_payeur_idx"), Flux.FLUX, new OrderField[] { Flux.FLUX.PAYEUR_ID }, false);
    public static final Index FLUX_RUN_IDX = Internal.createIndex(DSL.name("flux_run_idx"), Flux.FLUX, new OrderField[] { Flux.FLUX.RUN_ID }, false);
}
