/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core;


import fr.suivons.db.jooq.core.tables.Entreprise;
import fr.suivons.db.jooq.core.tables.Flux;
import fr.suivons.db.jooq.core.tables.Naf;
import fr.suivons.db.jooq.core.tables.Payeur;
import fr.suivons.db.jooq.core.tables.records.EntrepriseRecord;
import fr.suivons.db.jooq.core.tables.records.FluxRecord;
import fr.suivons.db.jooq.core.tables.records.NafRecord;
import fr.suivons.db.jooq.core.tables.records.PayeurRecord;
import fr.suivons.db.jooq.ops.tables.IngestionRun;
import fr.suivons.db.jooq.ops.tables.Source;
import fr.suivons.db.jooq.ops.tables.records.IngestionRunRecord;
import fr.suivons.db.jooq.ops.tables.records.SourceRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * core.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EntrepriseRecord> ENTREPRISE_PKEY = Internal.createUniqueKey(Entreprise.ENTREPRISE, DSL.name("entreprise_pkey"), new TableField[] { Entreprise.ENTREPRISE.SIREN }, true);
    public static final UniqueKey<FluxRecord> FLUX_PKEY = Internal.createUniqueKey(Flux.FLUX, DSL.name("flux_pkey"), new TableField[] { Flux.FLUX.ID, Flux.FLUX.ANNEE }, true);
    public static final UniqueKey<FluxRecord> FLUX_SOURCE_RECORD_UK = Internal.createUniqueKey(Flux.FLUX, DSL.name("flux_source_record_uk"), new TableField[] { Flux.FLUX.SOURCE_CODE, Flux.FLUX.SOURCE_RECORD_ID, Flux.FLUX.ANNEE }, true);
    public static final UniqueKey<NafRecord> NAF_PKEY = Internal.createUniqueKey(Naf.NAF, DSL.name("naf_pkey"), new TableField[] { Naf.NAF.NOMENCLATURE, Naf.NAF.CODE }, true);
    public static final UniqueKey<PayeurRecord> PAYEUR_IDENTIFIANT_KEY = Internal.createUniqueKey(Payeur.PAYEUR, DSL.name("payeur_identifiant_key"), new TableField[] { Payeur.PAYEUR.IDENTIFIANT }, true);
    public static final UniqueKey<PayeurRecord> PAYEUR_PKEY = Internal.createUniqueKey(Payeur.PAYEUR, DSL.name("payeur_pkey"), new TableField[] { Payeur.PAYEUR.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<FluxRecord, EntrepriseRecord> FLUX__FLUX_BENEFICIAIRE_SIREN_FKEY = Internal.createForeignKey(Flux.FLUX, DSL.name("flux_beneficiaire_siren_fkey"), new TableField[] { Flux.FLUX.BENEFICIAIRE_SIREN }, Keys.ENTREPRISE_PKEY, new TableField[] { Entreprise.ENTREPRISE.SIREN }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<FluxRecord, PayeurRecord> FLUX__FLUX_PAYEUR_ID_FKEY = Internal.createForeignKey(Flux.FLUX, DSL.name("flux_payeur_id_fkey"), new TableField[] { Flux.FLUX.PAYEUR_ID }, Keys.PAYEUR_PKEY, new TableField[] { Payeur.PAYEUR.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<FluxRecord, IngestionRunRecord> FLUX__FLUX_RUN_ID_FKEY = Internal.createForeignKey(Flux.FLUX, DSL.name("flux_run_id_fkey"), new TableField[] { Flux.FLUX.RUN_ID }, fr.suivons.db.jooq.ops.Keys.INGESTION_RUN_PKEY, new TableField[] { IngestionRun.INGESTION_RUN.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<FluxRecord, SourceRecord> FLUX__FLUX_SOURCE_CODE_FKEY = Internal.createForeignKey(Flux.FLUX, DSL.name("flux_source_code_fkey"), new TableField[] { Flux.FLUX.SOURCE_CODE }, fr.suivons.db.jooq.ops.Keys.SOURCE_PKEY, new TableField[] { Source.SOURCE.CODE }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
