/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core;


import fr.suivons.db.jooq.core.tables.Entreprise;
import fr.suivons.db.jooq.core.tables.Flux;
import fr.suivons.db.jooq.core.tables.Naf;
import fr.suivons.db.jooq.core.tables.Payeur;


/**
 * Convenience access to all tables in core.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Référentiel minimal des bénéficiaires (ADR 0004) ; identité détaillée lue
     * via l'API Sirene
     */
    public static final Entreprise ENTREPRISE = Entreprise.ENTREPRISE;

    /**
     * Flux d'argent public, chacun relié à sa source (provenance obligatoire)
     */
    public static final Flux FLUX = Flux.FLUX;

    /**
     * Nomenclature NAF (sous-classes), référentiel public statique
     */
    public static final Naf NAF = Naf.NAF;

    /**
     * Organismes payeurs : acheteurs publics, autorités d'octroi, programmes UE
     */
    public static final Payeur PAYEUR = Payeur.PAYEUR;
}
