/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.ops.tables;


import fr.suivons.db.jooq.core.tables.Flux.FluxPath;
import fr.suivons.db.jooq.ops.Indexes;
import fr.suivons.db.jooq.ops.Keys;
import fr.suivons.db.jooq.ops.Ops;
import fr.suivons.db.jooq.ops.tables.Rejet.RejetPath;
import fr.suivons.db.jooq.ops.tables.Source.SourcePath;
import fr.suivons.db.jooq.ops.tables.records.IngestionRunRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Exécutions des ingestions (pipeline SPEC §7.3), une ligne par run
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IngestionRun extends TableImpl<IngestionRunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ops.ingestion_run</code>
     */
    public static final IngestionRun INGESTION_RUN = new IngestionRun();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IngestionRunRecord> getRecordType() {
        return IngestionRunRecord.class;
    }

    /**
     * The column <code>ops.ingestion_run.id</code>.
     */
    public final TableField<IngestionRunRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedAlwaysAsIdentity(), this, "");

    /**
     * The column <code>ops.ingestion_run.source_code</code>.
     */
    public final TableField<IngestionRunRecord, String> SOURCE_CODE = createField(DSL.name("source_code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ops.ingestion_run.version_source</code>.
     */
    public final TableField<IngestionRunRecord, String> VERSION_SOURCE = createField(DSL.name("version_source"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ops.ingestion_run.debut</code>.
     */
    public final TableField<IngestionRunRecord, OffsetDateTime> DEBUT = createField(DSL.name("debut"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>ops.ingestion_run.fin</code>.
     */
    public final TableField<IngestionRunRecord, OffsetDateTime> FIN = createField(DSL.name("fin"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>ops.ingestion_run.statut</code>.
     */
    public final TableField<IngestionRunRecord, String> STATUT = createField(DSL.name("statut"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'EN_COURS'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>ops.ingestion_run.lus</code>.
     */
    public final TableField<IngestionRunRecord, Integer> LUS = createField(DSL.name("lus"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ops.ingestion_run.charges</code>.
     */
    public final TableField<IngestionRunRecord, Integer> CHARGES = createField(DSL.name("charges"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ops.ingestion_run.rejetes</code>.
     */
    public final TableField<IngestionRunRecord, Integer> REJETES = createField(DSL.name("rejetes"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ops.ingestion_run.checksum_fichier</code>.
     */
    public final TableField<IngestionRunRecord, String> CHECKSUM_FICHIER = createField(DSL.name("checksum_fichier"), SQLDataType.CLOB, this, "");

    private IngestionRun(Name alias, Table<IngestionRunRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IngestionRun(Name alias, Table<IngestionRunRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Exécutions des ingestions (pipeline SPEC §7.3), une ligne par run"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ops.ingestion_run</code> table reference
     */
    public IngestionRun(String alias) {
        this(DSL.name(alias), INGESTION_RUN);
    }

    /**
     * Create an aliased <code>ops.ingestion_run</code> table reference
     */
    public IngestionRun(Name alias) {
        this(alias, INGESTION_RUN);
    }

    /**
     * Create a <code>ops.ingestion_run</code> table reference
     */
    public IngestionRun() {
        this(DSL.name("ingestion_run"), null);
    }

    public <O extends Record> IngestionRun(Table<O> path, ForeignKey<O, IngestionRunRecord> childPath, InverseForeignKey<O, IngestionRunRecord> parentPath) {
        super(path, childPath, parentPath, INGESTION_RUN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IngestionRunPath extends IngestionRun implements Path<IngestionRunRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> IngestionRunPath(Table<O> path, ForeignKey<O, IngestionRunRecord> childPath, InverseForeignKey<O, IngestionRunRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IngestionRunPath(Name alias, Table<IngestionRunRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IngestionRunPath as(String alias) {
            return new IngestionRunPath(DSL.name(alias), this);
        }

        @Override
        public IngestionRunPath as(Name alias) {
            return new IngestionRunPath(alias, this);
        }

        @Override
        public IngestionRunPath as(Table<?> alias) {
            return new IngestionRunPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ops.OPS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.INGESTION_RUN_SOURCE_DEBUT_IDX);
    }

    @Override
    public Identity<IngestionRunRecord, Long> getIdentity() {
        return (Identity<IngestionRunRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<IngestionRunRecord> getPrimaryKey() {
        return Keys.INGESTION_RUN_PKEY;
    }

    @Override
    public List<ForeignKey<IngestionRunRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INGESTION_RUN__INGESTION_RUN_SOURCE_CODE_FKEY);
    }

    private transient SourcePath _source;

    /**
     * Get the implicit join path to the <code>ops.source</code> table.
     */
    public SourcePath source() {
        if (_source == null)
            _source = new SourcePath(this, Keys.INGESTION_RUN__INGESTION_RUN_SOURCE_CODE_FKEY, null);

        return _source;
    }

    private transient FluxPath _flux;

    /**
     * Get the implicit to-many join path to the <code>core.flux</code> table
     */
    public FluxPath flux() {
        if (_flux == null)
            _flux = new FluxPath(this, null, fr.suivons.db.jooq.core.Keys.FLUX__FLUX_RUN_ID_FKEY.getInverseKey());

        return _flux;
    }

    private transient RejetPath _rejet;

    /**
     * Get the implicit to-many join path to the <code>ops.rejet</code> table
     */
    public RejetPath rejet() {
        if (_rejet == null)
            _rejet = new RejetPath(this, null, Keys.REJET__REJET_RUN_ID_FKEY.getInverseKey());

        return _rejet;
    }

    @Override
    public List<Check<IngestionRunRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ingestion_run_compteurs_ck"), "(((lus >= 0) AND (charges >= 0) AND (rejetes >= 0)))", true),
            Internal.createCheck(this, DSL.name("ingestion_run_fin_ck"), "(((statut = 'EN_COURS'::text) = (fin IS NULL)))", true),
            Internal.createCheck(this, DSL.name("ingestion_run_statut_ck"), "((statut = ANY (ARRAY['EN_COURS'::text, 'SUCCES'::text, 'ECHEC'::text])))", true)
        );
    }

    @Override
    public IngestionRun as(String alias) {
        return new IngestionRun(DSL.name(alias), this);
    }

    @Override
    public IngestionRun as(Name alias) {
        return new IngestionRun(alias, this);
    }

    @Override
    public IngestionRun as(Table<?> alias) {
        return new IngestionRun(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IngestionRun rename(String name) {
        return new IngestionRun(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IngestionRun rename(Name name) {
        return new IngestionRun(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IngestionRun rename(Table<?> name) {
        return new IngestionRun(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IngestionRun where(Condition condition) {
        return new IngestionRun(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IngestionRun where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IngestionRun where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IngestionRun where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IngestionRun where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IngestionRun where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IngestionRun where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IngestionRun where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IngestionRun whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IngestionRun whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
