/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.ops.tables;


import fr.suivons.db.jooq.ops.Indexes;
import fr.suivons.db.jooq.ops.Keys;
import fr.suivons.db.jooq.ops.Ops;
import fr.suivons.db.jooq.ops.tables.IngestionRun.IngestionRunPath;
import fr.suivons.db.jooq.ops.tables.records.RejetRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Enregistrements source rejetés à la transformation, avec leur motif
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Rejet extends TableImpl<RejetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ops.rejet</code>
     */
    public static final Rejet REJET = new Rejet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RejetRecord> getRecordType() {
        return RejetRecord.class;
    }

    /**
     * The column <code>ops.rejet.id</code>.
     */
    public final TableField<RejetRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedAlwaysAsIdentity(), this, "");

    /**
     * The column <code>ops.rejet.run_id</code>.
     */
    public final TableField<RejetRecord, Long> RUN_ID = createField(DSL.name("run_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ops.rejet.source_record_id</code>.
     */
    public final TableField<RejetRecord, String> SOURCE_RECORD_ID = createField(DSL.name("source_record_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ops.rejet.motif</code>.
     */
    public final TableField<RejetRecord, String> MOTIF = createField(DSL.name("motif"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ops.rejet.payload</code>.
     */
    public final TableField<RejetRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>ops.rejet.cree_le</code>.
     */
    public final TableField<RejetRecord, OffsetDateTime> CREE_LE = createField(DSL.name("cree_le"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Rejet(Name alias, Table<RejetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Rejet(Name alias, Table<RejetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Enregistrements source rejetés à la transformation, avec leur motif"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ops.rejet</code> table reference
     */
    public Rejet(String alias) {
        this(DSL.name(alias), REJET);
    }

    /**
     * Create an aliased <code>ops.rejet</code> table reference
     */
    public Rejet(Name alias) {
        this(alias, REJET);
    }

    /**
     * Create a <code>ops.rejet</code> table reference
     */
    public Rejet() {
        this(DSL.name("rejet"), null);
    }

    public <O extends Record> Rejet(Table<O> path, ForeignKey<O, RejetRecord> childPath, InverseForeignKey<O, RejetRecord> parentPath) {
        super(path, childPath, parentPath, REJET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RejetPath extends Rejet implements Path<RejetRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RejetPath(Table<O> path, ForeignKey<O, RejetRecord> childPath, InverseForeignKey<O, RejetRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RejetPath(Name alias, Table<RejetRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RejetPath as(String alias) {
            return new RejetPath(DSL.name(alias), this);
        }

        @Override
        public RejetPath as(Name alias) {
            return new RejetPath(alias, this);
        }

        @Override
        public RejetPath as(Table<?> alias) {
            return new RejetPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ops.OPS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.REJET_RUN_IDX);
    }

    @Override
    public Identity<RejetRecord, Long> getIdentity() {
        return (Identity<RejetRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RejetRecord> getPrimaryKey() {
        return Keys.REJET_PKEY;
    }

    @Override
    public List<ForeignKey<RejetRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REJET__REJET_RUN_ID_FKEY);
    }

    private transient IngestionRunPath _ingestionRun;

    /**
     * Get the implicit join path to the <code>ops.ingestion_run</code> table.
     */
    public IngestionRunPath ingestionRun() {
        if (_ingestionRun == null)
            _ingestionRun = new IngestionRunPath(this, Keys.REJET__REJET_RUN_ID_FKEY, null);

        return _ingestionRun;
    }

    @Override
    public Rejet as(String alias) {
        return new Rejet(DSL.name(alias), this);
    }

    @Override
    public Rejet as(Name alias) {
        return new Rejet(alias, this);
    }

    @Override
    public Rejet as(Table<?> alias) {
        return new Rejet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rejet rename(String name) {
        return new Rejet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rejet rename(Name name) {
        return new Rejet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rejet rename(Table<?> name) {
        return new Rejet(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rejet where(Condition condition) {
        return new Rejet(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rejet where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rejet where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rejet where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rejet where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rejet where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rejet where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rejet where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rejet whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rejet whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
