/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.ops.tables;


import fr.suivons.db.jooq.core.tables.Flux.FluxPath;
import fr.suivons.db.jooq.ops.Keys;
import fr.suivons.db.jooq.ops.Ops;
import fr.suivons.db.jooq.ops.tables.IngestionRun.IngestionRunPath;
import fr.suivons.db.jooq.ops.tables.records.SourceRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Sources de données (flux et services d'appui), SPEC §4
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Source extends TableImpl<SourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ops.source</code>
     */
    public static final Source SOURCE = new Source();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SourceRecord> getRecordType() {
        return SourceRecord.class;
    }

    /**
     * The column <code>ops.source.code</code>.
     */
    public final TableField<SourceRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ops.source.libelle</code>.
     */
    public final TableField<SourceRecord, String> LIBELLE = createField(DSL.name("libelle"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ops.source.producteur</code>.
     */
    public final TableField<SourceRecord, String> PRODUCTEUR = createField(DSL.name("producteur"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ops.source.licence</code>.
     */
    public final TableField<SourceRecord, String> LICENCE = createField(DSL.name("licence"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ops.source.url_reference</code>.
     */
    public final TableField<SourceRecord, String> URL_REFERENCE = createField(DSL.name("url_reference"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ops.source.frequence</code>.
     */
    public final TableField<SourceRecord, String> FREQUENCE = createField(DSL.name("frequence"), SQLDataType.CLOB.nullable(false), this, "");

    private Source(Name alias, Table<SourceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Source(Name alias, Table<SourceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Sources de données (flux et services d'appui), SPEC §4"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ops.source</code> table reference
     */
    public Source(String alias) {
        this(DSL.name(alias), SOURCE);
    }

    /**
     * Create an aliased <code>ops.source</code> table reference
     */
    public Source(Name alias) {
        this(alias, SOURCE);
    }

    /**
     * Create a <code>ops.source</code> table reference
     */
    public Source() {
        this(DSL.name("source"), null);
    }

    public <O extends Record> Source(Table<O> path, ForeignKey<O, SourceRecord> childPath, InverseForeignKey<O, SourceRecord> parentPath) {
        super(path, childPath, parentPath, SOURCE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SourcePath extends Source implements Path<SourceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SourcePath(Table<O> path, ForeignKey<O, SourceRecord> childPath, InverseForeignKey<O, SourceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SourcePath(Name alias, Table<SourceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SourcePath as(String alias) {
            return new SourcePath(DSL.name(alias), this);
        }

        @Override
        public SourcePath as(Name alias) {
            return new SourcePath(alias, this);
        }

        @Override
        public SourcePath as(Table<?> alias) {
            return new SourcePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ops.OPS;
    }

    @Override
    public UniqueKey<SourceRecord> getPrimaryKey() {
        return Keys.SOURCE_PKEY;
    }

    private transient FluxPath _flux;

    /**
     * Get the implicit to-many join path to the <code>core.flux</code> table
     */
    public FluxPath flux() {
        if (_flux == null)
            _flux = new FluxPath(this, null, fr.suivons.db.jooq.core.Keys.FLUX__FLUX_SOURCE_CODE_FKEY.getInverseKey());

        return _flux;
    }

    private transient IngestionRunPath _ingestionRun;

    /**
     * Get the implicit to-many join path to the <code>ops.ingestion_run</code>
     * table
     */
    public IngestionRunPath ingestionRun() {
        if (_ingestionRun == null)
            _ingestionRun = new IngestionRunPath(this, null, Keys.INGESTION_RUN__INGESTION_RUN_SOURCE_CODE_FKEY.getInverseKey());

        return _ingestionRun;
    }

    @Override
    public Source as(String alias) {
        return new Source(DSL.name(alias), this);
    }

    @Override
    public Source as(Name alias) {
        return new Source(alias, this);
    }

    @Override
    public Source as(Table<?> alias) {
        return new Source(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Source rename(String name) {
        return new Source(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Source rename(Name name) {
        return new Source(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Source rename(Table<?> name) {
        return new Source(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Source where(Condition condition) {
        return new Source(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Source where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Source where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Source where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Source where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Source where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Source where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Source where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Source whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Source whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
