/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.raw.tables;


import fr.suivons.db.jooq.ops.tables.IngestionRun.IngestionRunPath;
import fr.suivons.db.jooq.raw.Keys;
import fr.suivons.db.jooq.raw.Raw;
import fr.suivons.db.jooq.raw.tables.records.DecpRecordRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * DECP : un enregistrement par couple (marché, titulaire), après fusion des
 * lignes du jeu
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DecpRecord extends TableImpl<DecpRecordRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>raw.decp_record</code>
     */
    public static final DecpRecord DECP_RECORD = new DecpRecord();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DecpRecordRecord> getRecordType() {
        return DecpRecordRecord.class;
    }

    /**
     * The column <code>raw.decp_record.source_record_id</code>.
     */
    public final TableField<DecpRecordRecord, String> SOURCE_RECORD_ID = createField(DSL.name("source_record_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>raw.decp_record.run_id</code>.
     */
    public final TableField<DecpRecordRecord, Long> RUN_ID = createField(DSL.name("run_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>raw.decp_record.payload</code>.
     */
    public final TableField<DecpRecordRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>raw.decp_record.checksum</code>.
     */
    public final TableField<DecpRecordRecord, String> CHECKSUM = createField(DSL.name("checksum"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>raw.decp_record.recu_le</code>.
     */
    public final TableField<DecpRecordRecord, OffsetDateTime> RECU_LE = createField(DSL.name("recu_le"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private DecpRecord(Name alias, Table<DecpRecordRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DecpRecord(Name alias, Table<DecpRecordRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("DECP : un enregistrement par couple (marché, titulaire), après fusion des lignes du jeu"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>raw.decp_record</code> table reference
     */
    public DecpRecord(String alias) {
        this(DSL.name(alias), DECP_RECORD);
    }

    /**
     * Create an aliased <code>raw.decp_record</code> table reference
     */
    public DecpRecord(Name alias) {
        this(alias, DECP_RECORD);
    }

    /**
     * Create a <code>raw.decp_record</code> table reference
     */
    public DecpRecord() {
        this(DSL.name("decp_record"), null);
    }

    public <O extends Record> DecpRecord(Table<O> path, ForeignKey<O, DecpRecordRecord> childPath, InverseForeignKey<O, DecpRecordRecord> parentPath) {
        super(path, childPath, parentPath, DECP_RECORD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DecpRecordPath extends DecpRecord implements Path<DecpRecordRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DecpRecordPath(Table<O> path, ForeignKey<O, DecpRecordRecord> childPath, InverseForeignKey<O, DecpRecordRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DecpRecordPath(Name alias, Table<DecpRecordRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DecpRecordPath as(String alias) {
            return new DecpRecordPath(DSL.name(alias), this);
        }

        @Override
        public DecpRecordPath as(Name alias) {
            return new DecpRecordPath(alias, this);
        }

        @Override
        public DecpRecordPath as(Table<?> alias) {
            return new DecpRecordPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Raw.RAW;
    }

    @Override
    public UniqueKey<DecpRecordRecord> getPrimaryKey() {
        return Keys.DECP_RECORD_PKEY;
    }

    @Override
    public List<ForeignKey<DecpRecordRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DECP_RECORD__DECP_RECORD_RUN_ID_FKEY);
    }

    private transient IngestionRunPath _ingestionRun;

    /**
     * Get the implicit join path to the <code>ops.ingestion_run</code> table.
     */
    public IngestionRunPath ingestionRun() {
        if (_ingestionRun == null)
            _ingestionRun = new IngestionRunPath(this, Keys.DECP_RECORD__DECP_RECORD_RUN_ID_FKEY, null);

        return _ingestionRun;
    }

    @Override
    public DecpRecord as(String alias) {
        return new DecpRecord(DSL.name(alias), this);
    }

    @Override
    public DecpRecord as(Name alias) {
        return new DecpRecord(alias, this);
    }

    @Override
    public DecpRecord as(Table<?> alias) {
        return new DecpRecord(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DecpRecord rename(String name) {
        return new DecpRecord(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DecpRecord rename(Name name) {
        return new DecpRecord(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DecpRecord rename(Table<?> name) {
        return new DecpRecord(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DecpRecord where(Condition condition) {
        return new DecpRecord(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DecpRecord where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DecpRecord where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DecpRecord where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DecpRecord where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DecpRecord where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DecpRecord where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DecpRecord where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DecpRecord whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DecpRecord whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
