/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core.tables.records;


import fr.suivons.db.jooq.core.tables.Entreprise;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Référentiel minimal des bénéficiaires (ADR 0004) ; identité détaillée lue via
 * l'API Sirene
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EntrepriseRecord extends UpdatableRecordImpl<EntrepriseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>core.entreprise.siren</code>.
     */
    public void setSiren(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>core.entreprise.siren</code>.
     */
    public String getSiren() {
        return (String) get(0);
    }

    /**
     * Setter for <code>core.entreprise.denomination</code>.
     */
    public void setDenomination(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>core.entreprise.denomination</code>.
     */
    public String getDenomination() {
        return (String) get(1);
    }

    /**
     * Setter for <code>core.entreprise.naf_code</code>.
     */
    public void setNafCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>core.entreprise.naf_code</code>.
     */
    public String getNafCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>core.entreprise.naf_nomenclature</code>.
     */
    public void setNafNomenclature(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>core.entreprise.naf_nomenclature</code>.
     */
    public String getNafNomenclature() {
        return (String) get(3);
    }

    /**
     * Setter for <code>core.entreprise.commune_siege</code>.
     */
    public void setCommuneSiege(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>core.entreprise.commune_siege</code>.
     */
    public String getCommuneSiege() {
        return (String) get(4);
    }

    /**
     * Setter for <code>core.entreprise.departement_siege</code>.
     */
    public void setDepartementSiege(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>core.entreprise.departement_siege</code>.
     */
    public String getDepartementSiege() {
        return (String) get(5);
    }

    /**
     * Setter for <code>core.entreprise.etat</code>.
     */
    public void setEtat(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>core.entreprise.etat</code>.
     */
    public String getEtat() {
        return (String) get(6);
    }

    /**
     * Setter for <code>core.entreprise.diffusible</code>. Faux si
     * statutDiffusionUniteLegale = P : aucune donnée nominative exposée
     */
    public void setDiffusible(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>core.entreprise.diffusible</code>. Faux si
     * statutDiffusionUniteLegale = P : aucune donnée nominative exposée
     */
    public Boolean getDiffusible() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>core.entreprise.personne_physique</code>. Vrai si
     * catégorie juridique 1000 (entrepreneur individuel) : aucune donnée
     * nominative exposée
     */
    public void setPersonnePhysique(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>core.entreprise.personne_physique</code>. Vrai si
     * catégorie juridique 1000 (entrepreneur individuel) : aucune donnée
     * nominative exposée
     */
    public Boolean getPersonnePhysique() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>core.entreprise.rafraichi_le</code>.
     */
    public void setRafraichiLe(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>core.entreprise.rafraichi_le</code>.
     */
    public OffsetDateTime getRafraichiLe() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntrepriseRecord
     */
    public EntrepriseRecord() {
        super(Entreprise.ENTREPRISE);
    }

    /**
     * Create a detached, initialised EntrepriseRecord
     */
    public EntrepriseRecord(String siren, String denomination, String nafCode, String nafNomenclature, String communeSiege, String departementSiege, String etat, Boolean diffusible, Boolean personnePhysique, OffsetDateTime rafraichiLe) {
        super(Entreprise.ENTREPRISE);

        setSiren(siren);
        setDenomination(denomination);
        setNafCode(nafCode);
        setNafNomenclature(nafNomenclature);
        setCommuneSiege(communeSiege);
        setDepartementSiege(departementSiege);
        setEtat(etat);
        setDiffusible(diffusible);
        setPersonnePhysique(personnePhysique);
        setRafraichiLe(rafraichiLe);
        resetTouchedOnNotNull();
    }
}
