/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core.tables.records;


import fr.suivons.db.jooq.core.tables.Flux;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Flux d'argent public, chacun relié à sa source (provenance obligatoire)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FluxRecord extends UpdatableRecordImpl<FluxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>core.flux.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>core.flux.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>core.flux.canal</code>.
     */
    public void setCanal(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>core.flux.canal</code>.
     */
    public String getCanal() {
        return (String) get(1);
    }

    /**
     * Setter for <code>core.flux.beneficiaire_siren</code>.
     */
    public void setBeneficiaireSiren(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>core.flux.beneficiaire_siren</code>.
     */
    public String getBeneficiaireSiren() {
        return (String) get(2);
    }

    /**
     * Setter for <code>core.flux.beneficiaire_nom_source</code>.
     */
    public void setBeneficiaireNomSource(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>core.flux.beneficiaire_nom_source</code>.
     */
    public String getBeneficiaireNomSource() {
        return (String) get(3);
    }

    /**
     * Setter for <code>core.flux.payeur_id</code>.
     */
    public void setPayeurId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>core.flux.payeur_id</code>.
     */
    public Long getPayeurId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>core.flux.objet</code>.
     */
    public void setObjet(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>core.flux.objet</code>.
     */
    public String getObjet() {
        return (String) get(5);
    }

    /**
     * Setter for <code>core.flux.date_flux</code>.
     */
    public void setDateFlux(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>core.flux.date_flux</code>.
     */
    public LocalDate getDateFlux() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>core.flux.annee</code>.
     */
    public void setAnnee(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>core.flux.annee</code>.
     */
    public Short getAnnee() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>core.flux.montant_ferme</code>.
     */
    public void setMontantFerme(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>core.flux.montant_ferme</code>.
     */
    public Long getMontantFerme() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>core.flux.montant_plafond</code>.
     */
    public void setMontantPlafond(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>core.flux.montant_plafond</code>.
     */
    public Long getMontantPlafond() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>core.flux.nature_montant</code>.
     */
    public void setNatureMontant(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>core.flux.nature_montant</code>.
     */
    public String getNatureMontant() {
        return (String) get(10);
    }

    /**
     * Setter for <code>core.flux.qualite</code>.
     */
    public void setQualite(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>core.flux.qualite</code>.
     */
    public String getQualite() {
        return (String) get(11);
    }

    /**
     * Setter for <code>core.flux.rattachement</code>.
     */
    public void setRattachement(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>core.flux.rattachement</code>.
     */
    public String getRattachement() {
        return (String) get(12);
    }

    /**
     * Setter for <code>core.flux.confiance_rattachement</code>.
     */
    public void setConfianceRattachement(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>core.flux.confiance_rattachement</code>.
     */
    public BigDecimal getConfianceRattachement() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>core.flux.source_code</code>.
     */
    public void setSourceCode(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>core.flux.source_code</code>.
     */
    public String getSourceCode() {
        return (String) get(14);
    }

    /**
     * Setter for <code>core.flux.source_record_id</code>.
     */
    public void setSourceRecordId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>core.flux.source_record_id</code>.
     */
    public String getSourceRecordId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>core.flux.source_url</code>.
     */
    public void setSourceUrl(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>core.flux.source_url</code>.
     */
    public String getSourceUrl() {
        return (String) get(16);
    }

    /**
     * Setter for <code>core.flux.run_id</code>.
     */
    public void setRunId(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>core.flux.run_id</code>.
     */
    public Long getRunId() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>core.flux.extrait_le</code>.
     */
    public void setExtraitLe(OffsetDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>core.flux.extrait_le</code>.
     */
    public OffsetDateTime getExtraitLe() {
        return (OffsetDateTime) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Short> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FluxRecord
     */
    public FluxRecord() {
        super(Flux.FLUX);
    }

    /**
     * Create a detached, initialised FluxRecord
     */
    public FluxRecord(Long id, String canal, String beneficiaireSiren, String beneficiaireNomSource, Long payeurId, String objet, LocalDate dateFlux, Short annee, Long montantFerme, Long montantPlafond, String natureMontant, String qualite, String rattachement, BigDecimal confianceRattachement, String sourceCode, String sourceRecordId, String sourceUrl, Long runId, OffsetDateTime extraitLe) {
        super(Flux.FLUX);

        setId(id);
        setCanal(canal);
        setBeneficiaireSiren(beneficiaireSiren);
        setBeneficiaireNomSource(beneficiaireNomSource);
        setPayeurId(payeurId);
        setObjet(objet);
        setDateFlux(dateFlux);
        setAnnee(annee);
        setMontantFerme(montantFerme);
        setMontantPlafond(montantPlafond);
        setNatureMontant(natureMontant);
        setQualite(qualite);
        setRattachement(rattachement);
        setConfianceRattachement(confianceRattachement);
        setSourceCode(sourceCode);
        setSourceRecordId(sourceRecordId);
        setSourceUrl(sourceUrl);
        setRunId(runId);
        setExtraitLe(extraitLe);
        resetTouchedOnNotNull();
    }
}
