/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core.tables.records;


import fr.suivons.db.jooq.core.tables.Naf;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Nomenclature NAF (sous-classes), référentiel public statique
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NafRecord extends UpdatableRecordImpl<NafRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>core.naf.nomenclature</code>.
     */
    public void setNomenclature(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>core.naf.nomenclature</code>.
     */
    public String getNomenclature() {
        return (String) get(0);
    }

    /**
     * Setter for <code>core.naf.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>core.naf.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>core.naf.libelle</code>.
     */
    public void setLibelle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>core.naf.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NafRecord
     */
    public NafRecord() {
        super(Naf.NAF);
    }

    /**
     * Create a detached, initialised NafRecord
     */
    public NafRecord(String nomenclature, String code, String libelle) {
        super(Naf.NAF);

        setNomenclature(nomenclature);
        setCode(code);
        setLibelle(libelle);
        resetTouchedOnNotNull();
    }
}
