/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core.tables.records;


import fr.suivons.db.jooq.core.tables.Payeur;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Organismes payeurs : acheteurs publics, autorités d'octroi, programmes UE
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PayeurRecord extends UpdatableRecordImpl<PayeurRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>core.payeur.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>core.payeur.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>core.payeur.identifiant</code>.
     */
    public void setIdentifiant(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>core.payeur.identifiant</code>.
     */
    public String getIdentifiant() {
        return (String) get(1);
    }

    /**
     * Setter for <code>core.payeur.nom</code>.
     */
    public void setNom(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>core.payeur.nom</code>.
     */
    public String getNom() {
        return (String) get(2);
    }

    /**
     * Setter for <code>core.payeur.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>core.payeur.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PayeurRecord
     */
    public PayeurRecord() {
        super(Payeur.PAYEUR);
    }

    /**
     * Create a detached, initialised PayeurRecord
     */
    public PayeurRecord(Long id, String identifiant, String nom, String type) {
        super(Payeur.PAYEUR);

        setId(id);
        setIdentifiant(identifiant);
        setNom(nom);
        setType(type);
        resetTouchedOnNotNull();
    }
}
