/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core.tables;


import fr.suivons.db.jooq.core.Core;
import fr.suivons.db.jooq.core.Keys;
import fr.suivons.db.jooq.core.tables.Flux.FluxPath;
import fr.suivons.db.jooq.core.tables.records.EntrepriseRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Référentiel minimal des bénéficiaires (ADR 0004) ; identité détaillée lue via
 * l'API Sirene
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Entreprise extends TableImpl<EntrepriseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>core.entreprise</code>
     */
    public static final Entreprise ENTREPRISE = new Entreprise();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntrepriseRecord> getRecordType() {
        return EntrepriseRecord.class;
    }

    /**
     * The column <code>core.entreprise.siren</code>.
     */
    public final TableField<EntrepriseRecord, String> SIREN = createField(DSL.name("siren"), SQLDataType.CHAR(9).nullable(false), this, "");

    /**
     * The column <code>core.entreprise.denomination</code>.
     */
    public final TableField<EntrepriseRecord, String> DENOMINATION = createField(DSL.name("denomination"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>core.entreprise.naf_code</code>.
     */
    public final TableField<EntrepriseRecord, String> NAF_CODE = createField(DSL.name("naf_code"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>core.entreprise.naf_nomenclature</code>.
     */
    public final TableField<EntrepriseRecord, String> NAF_NOMENCLATURE = createField(DSL.name("naf_nomenclature"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>core.entreprise.commune_siege</code>.
     */
    public final TableField<EntrepriseRecord, String> COMMUNE_SIEGE = createField(DSL.name("commune_siege"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>core.entreprise.departement_siege</code>.
     */
    public final TableField<EntrepriseRecord, String> DEPARTEMENT_SIEGE = createField(DSL.name("departement_siege"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>core.entreprise.etat</code>.
     */
    public final TableField<EntrepriseRecord, String> ETAT = createField(DSL.name("etat"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>core.entreprise.diffusible</code>. Faux si
     * statutDiffusionUniteLegale = P : aucune donnée nominative exposée
     */
    public final TableField<EntrepriseRecord, Boolean> DIFFUSIBLE = createField(DSL.name("diffusible"), SQLDataType.BOOLEAN.nullable(false), this, "Faux si statutDiffusionUniteLegale = P : aucune donnée nominative exposée");

    /**
     * The column <code>core.entreprise.personne_physique</code>. Vrai si
     * catégorie juridique 1000 (entrepreneur individuel) : aucune donnée
     * nominative exposée
     */
    public final TableField<EntrepriseRecord, Boolean> PERSONNE_PHYSIQUE = createField(DSL.name("personne_physique"), SQLDataType.BOOLEAN.nullable(false), this, "Vrai si catégorie juridique 1000 (entrepreneur individuel) : aucune donnée nominative exposée");

    /**
     * The column <code>core.entreprise.rafraichi_le</code>.
     */
    public final TableField<EntrepriseRecord, OffsetDateTime> RAFRAICHI_LE = createField(DSL.name("rafraichi_le"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private Entreprise(Name alias, Table<EntrepriseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Entreprise(Name alias, Table<EntrepriseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Référentiel minimal des bénéficiaires (ADR 0004) ; identité détaillée lue via l'API Sirene"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>core.entreprise</code> table reference
     */
    public Entreprise(String alias) {
        this(DSL.name(alias), ENTREPRISE);
    }

    /**
     * Create an aliased <code>core.entreprise</code> table reference
     */
    public Entreprise(Name alias) {
        this(alias, ENTREPRISE);
    }

    /**
     * Create a <code>core.entreprise</code> table reference
     */
    public Entreprise() {
        this(DSL.name("entreprise"), null);
    }

    public <O extends Record> Entreprise(Table<O> path, ForeignKey<O, EntrepriseRecord> childPath, InverseForeignKey<O, EntrepriseRecord> parentPath) {
        super(path, childPath, parentPath, ENTREPRISE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EntreprisePath extends Entreprise implements Path<EntrepriseRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EntreprisePath(Table<O> path, ForeignKey<O, EntrepriseRecord> childPath, InverseForeignKey<O, EntrepriseRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EntreprisePath(Name alias, Table<EntrepriseRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EntreprisePath as(String alias) {
            return new EntreprisePath(DSL.name(alias), this);
        }

        @Override
        public EntreprisePath as(Name alias) {
            return new EntreprisePath(alias, this);
        }

        @Override
        public EntreprisePath as(Table<?> alias) {
            return new EntreprisePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Core.CORE;
    }

    @Override
    public UniqueKey<EntrepriseRecord> getPrimaryKey() {
        return Keys.ENTREPRISE_PKEY;
    }

    private transient FluxPath _flux;

    /**
     * Get the implicit to-many join path to the <code>core.flux</code> table
     */
    public FluxPath flux() {
        if (_flux == null)
            _flux = new FluxPath(this, null, Keys.FLUX__FLUX_BENEFICIAIRE_SIREN_FKEY.getInverseKey());

        return _flux;
    }

    @Override
    public List<Check<EntrepriseRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("entreprise_etat_ck"), "((etat = ANY (ARRAY['ACTIVE'::text, 'CESSEE'::text])))", true),
            Internal.createCheck(this, DSL.name("entreprise_naf_ck"), "(((naf_code IS NULL) = (naf_nomenclature IS NULL)))", true),
            Internal.createCheck(this, DSL.name("entreprise_naf_nomenclature_ck"), "((naf_nomenclature = ANY (ARRAY['NAFRev2'::text, 'NAF2025'::text])))", true),
            Internal.createCheck(this, DSL.name("entreprise_siren_ck"), "((siren ~ '^[0-9]{9}$'::text))", true)
        );
    }

    @Override
    public Entreprise as(String alias) {
        return new Entreprise(DSL.name(alias), this);
    }

    @Override
    public Entreprise as(Name alias) {
        return new Entreprise(alias, this);
    }

    @Override
    public Entreprise as(Table<?> alias) {
        return new Entreprise(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Entreprise rename(String name) {
        return new Entreprise(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Entreprise rename(Name name) {
        return new Entreprise(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Entreprise rename(Table<?> name) {
        return new Entreprise(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entreprise where(Condition condition) {
        return new Entreprise(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entreprise where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entreprise where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entreprise where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entreprise where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entreprise where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entreprise where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entreprise where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entreprise whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entreprise whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
