/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core.tables;


import fr.suivons.db.jooq.core.Core;
import fr.suivons.db.jooq.core.Indexes;
import fr.suivons.db.jooq.core.Keys;
import fr.suivons.db.jooq.core.tables.Entreprise.EntreprisePath;
import fr.suivons.db.jooq.core.tables.Payeur.PayeurPath;
import fr.suivons.db.jooq.core.tables.records.FluxRecord;
import fr.suivons.db.jooq.ops.tables.IngestionRun.IngestionRunPath;
import fr.suivons.db.jooq.ops.tables.Source.SourcePath;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Flux d'argent public, chacun relié à sa source (provenance obligatoire)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Flux extends TableImpl<FluxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>core.flux</code>
     */
    public static final Flux FLUX = new Flux();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FluxRecord> getRecordType() {
        return FluxRecord.class;
    }

    /**
     * The column <code>core.flux.id</code>.
     */
    public final TableField<FluxRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedAlwaysAsIdentity(), this, "");

    /**
     * The column <code>core.flux.canal</code>.
     */
    public final TableField<FluxRecord, String> CANAL = createField(DSL.name("canal"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>core.flux.beneficiaire_siren</code>.
     */
    public final TableField<FluxRecord, String> BENEFICIAIRE_SIREN = createField(DSL.name("beneficiaire_siren"), SQLDataType.CHAR(9), this, "");

    /**
     * The column <code>core.flux.beneficiaire_nom_source</code>.
     */
    public final TableField<FluxRecord, String> BENEFICIAIRE_NOM_SOURCE = createField(DSL.name("beneficiaire_nom_source"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>core.flux.payeur_id</code>.
     */
    public final TableField<FluxRecord, Long> PAYEUR_ID = createField(DSL.name("payeur_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>core.flux.objet</code>.
     */
    public final TableField<FluxRecord, String> OBJET = createField(DSL.name("objet"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>core.flux.date_flux</code>.
     */
    public final TableField<FluxRecord, LocalDate> DATE_FLUX = createField(DSL.name("date_flux"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>core.flux.annee</code>.
     */
    public final TableField<FluxRecord, Short> ANNEE = createField(DSL.name("annee"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>core.flux.montant_ferme</code>.
     */
    public final TableField<FluxRecord, Long> MONTANT_FERME = createField(DSL.name("montant_ferme"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>core.flux.montant_plafond</code>.
     */
    public final TableField<FluxRecord, Long> MONTANT_PLAFOND = createField(DSL.name("montant_plafond"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>core.flux.nature_montant</code>.
     */
    public final TableField<FluxRecord, String> NATURE_MONTANT = createField(DSL.name("nature_montant"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>core.flux.qualite</code>.
     */
    public final TableField<FluxRecord, String> QUALITE = createField(DSL.name("qualite"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'OK'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>core.flux.rattachement</code>.
     */
    public final TableField<FluxRecord, String> RATTACHEMENT = createField(DSL.name("rattachement"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>core.flux.confiance_rattachement</code>.
     */
    public final TableField<FluxRecord, BigDecimal> CONFIANCE_RATTACHEMENT = createField(DSL.name("confiance_rattachement"), SQLDataType.NUMERIC(4, 3), this, "");

    /**
     * The column <code>core.flux.source_code</code>.
     */
    public final TableField<FluxRecord, String> SOURCE_CODE = createField(DSL.name("source_code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>core.flux.source_record_id</code>.
     */
    public final TableField<FluxRecord, String> SOURCE_RECORD_ID = createField(DSL.name("source_record_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>core.flux.source_url</code>.
     */
    public final TableField<FluxRecord, String> SOURCE_URL = createField(DSL.name("source_url"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>core.flux.run_id</code>.
     */
    public final TableField<FluxRecord, Long> RUN_ID = createField(DSL.name("run_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>core.flux.extrait_le</code>.
     */
    public final TableField<FluxRecord, OffsetDateTime> EXTRAIT_LE = createField(DSL.name("extrait_le"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private Flux(Name alias, Table<FluxRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Flux(Name alias, Table<FluxRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Flux d'argent public, chacun relié à sa source (provenance obligatoire)"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>core.flux</code> table reference
     */
    public Flux(String alias) {
        this(DSL.name(alias), FLUX);
    }

    /**
     * Create an aliased <code>core.flux</code> table reference
     */
    public Flux(Name alias) {
        this(alias, FLUX);
    }

    /**
     * Create a <code>core.flux</code> table reference
     */
    public Flux() {
        this(DSL.name("flux"), null);
    }

    public <O extends Record> Flux(Table<O> path, ForeignKey<O, FluxRecord> childPath, InverseForeignKey<O, FluxRecord> parentPath) {
        super(path, childPath, parentPath, FLUX);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FluxPath extends Flux implements Path<FluxRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FluxPath(Table<O> path, ForeignKey<O, FluxRecord> childPath, InverseForeignKey<O, FluxRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FluxPath(Name alias, Table<FluxRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FluxPath as(String alias) {
            return new FluxPath(DSL.name(alias), this);
        }

        @Override
        public FluxPath as(Name alias) {
            return new FluxPath(alias, this);
        }

        @Override
        public FluxPath as(Table<?> alias) {
            return new FluxPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Core.CORE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FLUX_BENEFICIAIRE_IDX, Indexes.FLUX_PAYEUR_IDX, Indexes.FLUX_RUN_IDX);
    }

    @Override
    public Identity<FluxRecord, Long> getIdentity() {
        return (Identity<FluxRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FluxRecord> getPrimaryKey() {
        return Keys.FLUX_PKEY;
    }

    @Override
    public List<UniqueKey<FluxRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FLUX_SOURCE_RECORD_UK);
    }

    @Override
    public List<ForeignKey<FluxRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FLUX__FLUX_BENEFICIAIRE_SIREN_FKEY, Keys.FLUX__FLUX_PAYEUR_ID_FKEY, Keys.FLUX__FLUX_RUN_ID_FKEY, Keys.FLUX__FLUX_SOURCE_CODE_FKEY);
    }

    private transient EntreprisePath _entreprise;

    /**
     * Get the implicit join path to the <code>core.entreprise</code> table.
     */
    public EntreprisePath entreprise() {
        if (_entreprise == null)
            _entreprise = new EntreprisePath(this, Keys.FLUX__FLUX_BENEFICIAIRE_SIREN_FKEY, null);

        return _entreprise;
    }

    private transient PayeurPath _payeur;

    /**
     * Get the implicit join path to the <code>core.payeur</code> table.
     */
    public PayeurPath payeur() {
        if (_payeur == null)
            _payeur = new PayeurPath(this, Keys.FLUX__FLUX_PAYEUR_ID_FKEY, null);

        return _payeur;
    }

    private transient IngestionRunPath _ingestionRun;

    /**
     * Get the implicit join path to the <code>ops.ingestion_run</code> table.
     */
    public IngestionRunPath ingestionRun() {
        if (_ingestionRun == null)
            _ingestionRun = new IngestionRunPath(this, Keys.FLUX__FLUX_RUN_ID_FKEY, null);

        return _ingestionRun;
    }

    private transient SourcePath _source;

    /**
     * Get the implicit join path to the <code>ops.source</code> table.
     */
    public SourcePath source() {
        if (_source == null)
            _source = new SourcePath(this, Keys.FLUX__FLUX_SOURCE_CODE_FKEY, null);

        return _source;
    }

    @Override
    public List<Check<FluxRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("flux_annee_ck"), "(((annee)::numeric = EXTRACT(year FROM date_flux)))", true),
            Internal.createCheck(this, DSL.name("flux_bornes_ck"), "((montant_ferme <= montant_plafond))", true),
            Internal.createCheck(this, DSL.name("flux_canal_ck"), "((canal = ANY (ARRAY['MARCHE'::text, 'AIDE_ETAT'::text, 'FONDS_UE'::text])))", true),
            Internal.createCheck(this, DSL.name("flux_confiance_ck"), "(((confiance_rattachement >= (0)::numeric) AND (confiance_rattachement <= (1)::numeric)))", true),
            Internal.createCheck(this, DSL.name("flux_confiance_source_ck"), "(((rattachement <> 'SIREN_SOURCE'::text) OR (confiance_rattachement = (1)::numeric)))", true),
            Internal.createCheck(this, DSL.name("flux_ferme_ck"), "(((nature_montant <> 'FERME'::text) OR (montant_ferme = montant_plafond)))", true),
            Internal.createCheck(this, DSL.name("flux_montants_positifs_ck"), "(((montant_ferme >= 0) AND (montant_plafond >= 0)))", true),
            Internal.createCheck(this, DSL.name("flux_nature_ck"), "((nature_montant = ANY (ARRAY['FERME'::text, 'PLAFOND'::text, 'PARTAGE'::text, 'INCONNU'::text])))", true),
            Internal.createCheck(this, DSL.name("flux_plafond_ck"), "(((nature_montant = 'INCONNU'::text) OR (montant_plafond IS NOT NULL)))", true),
            Internal.createCheck(this, DSL.name("flux_qualite_ck"), "((qualite = ANY (ARRAY['OK'::text, 'ABERRANT'::text])))", true),
            Internal.createCheck(this, DSL.name("flux_rattachement_ck"), "((rattachement = ANY (ARRAY['SIREN_SOURCE'::text, 'RESOLU_AUTO'::text, 'NON_RESOLU'::text])))", true),
            Internal.createCheck(this, DSL.name("flux_rattachement_siren_ck"), "(((rattachement = 'NON_RESOLU'::text) = (beneficiaire_siren IS NULL)))", true)
        );
    }

    @Override
    public Flux as(String alias) {
        return new Flux(DSL.name(alias), this);
    }

    @Override
    public Flux as(Name alias) {
        return new Flux(alias, this);
    }

    @Override
    public Flux as(Table<?> alias) {
        return new Flux(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Flux rename(String name) {
        return new Flux(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Flux rename(Name name) {
        return new Flux(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Flux rename(Table<?> name) {
        return new Flux(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Flux where(Condition condition) {
        return new Flux(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Flux where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Flux where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Flux where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Flux where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Flux where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Flux where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Flux where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Flux whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Flux whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
