/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core.tables;


import fr.suivons.db.jooq.core.Core;
import fr.suivons.db.jooq.core.Keys;
import fr.suivons.db.jooq.core.tables.records.NafRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Nomenclature NAF (sous-classes), référentiel public statique
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Naf extends TableImpl<NafRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>core.naf</code>
     */
    public static final Naf NAF = new Naf();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NafRecord> getRecordType() {
        return NafRecord.class;
    }

    /**
     * The column <code>core.naf.nomenclature</code>.
     */
    public final TableField<NafRecord, String> NOMENCLATURE = createField(DSL.name("nomenclature"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>core.naf.code</code>.
     */
    public final TableField<NafRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>core.naf.libelle</code>.
     */
    public final TableField<NafRecord, String> LIBELLE = createField(DSL.name("libelle"), SQLDataType.CLOB.nullable(false), this, "");

    private Naf(Name alias, Table<NafRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Naf(Name alias, Table<NafRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Nomenclature NAF (sous-classes), référentiel public statique"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>core.naf</code> table reference
     */
    public Naf(String alias) {
        this(DSL.name(alias), NAF);
    }

    /**
     * Create an aliased <code>core.naf</code> table reference
     */
    public Naf(Name alias) {
        this(alias, NAF);
    }

    /**
     * Create a <code>core.naf</code> table reference
     */
    public Naf() {
        this(DSL.name("naf"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Core.CORE;
    }

    @Override
    public UniqueKey<NafRecord> getPrimaryKey() {
        return Keys.NAF_PKEY;
    }

    @Override
    public List<Check<NafRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("naf_nomenclature_ck"), "((nomenclature = ANY (ARRAY['NAFRev2'::text, 'NAF2025'::text])))", true)
        );
    }

    @Override
    public Naf as(String alias) {
        return new Naf(DSL.name(alias), this);
    }

    @Override
    public Naf as(Name alias) {
        return new Naf(alias, this);
    }

    @Override
    public Naf as(Table<?> alias) {
        return new Naf(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Naf rename(String name) {
        return new Naf(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Naf rename(Name name) {
        return new Naf(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Naf rename(Table<?> name) {
        return new Naf(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Naf where(Condition condition) {
        return new Naf(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Naf where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Naf where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Naf where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Naf where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Naf where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Naf where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Naf where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Naf whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Naf whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
