/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq.core.tables;


import fr.suivons.db.jooq.core.Core;
import fr.suivons.db.jooq.core.Keys;
import fr.suivons.db.jooq.core.tables.Flux.FluxPath;
import fr.suivons.db.jooq.core.tables.records.PayeurRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Organismes payeurs : acheteurs publics, autorités d'octroi, programmes UE
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Payeur extends TableImpl<PayeurRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>core.payeur</code>
     */
    public static final Payeur PAYEUR = new Payeur();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PayeurRecord> getRecordType() {
        return PayeurRecord.class;
    }

    /**
     * The column <code>core.payeur.id</code>.
     */
    public final TableField<PayeurRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedAlwaysAsIdentity(), this, "");

    /**
     * The column <code>core.payeur.identifiant</code>.
     */
    public final TableField<PayeurRecord, String> IDENTIFIANT = createField(DSL.name("identifiant"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>core.payeur.nom</code>.
     */
    public final TableField<PayeurRecord, String> NOM = createField(DSL.name("nom"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>core.payeur.type</code>.
     */
    public final TableField<PayeurRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    private Payeur(Name alias, Table<PayeurRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Payeur(Name alias, Table<PayeurRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Organismes payeurs : acheteurs publics, autorités d'octroi, programmes UE"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>core.payeur</code> table reference
     */
    public Payeur(String alias) {
        this(DSL.name(alias), PAYEUR);
    }

    /**
     * Create an aliased <code>core.payeur</code> table reference
     */
    public Payeur(Name alias) {
        this(alias, PAYEUR);
    }

    /**
     * Create a <code>core.payeur</code> table reference
     */
    public Payeur() {
        this(DSL.name("payeur"), null);
    }

    public <O extends Record> Payeur(Table<O> path, ForeignKey<O, PayeurRecord> childPath, InverseForeignKey<O, PayeurRecord> parentPath) {
        super(path, childPath, parentPath, PAYEUR);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PayeurPath extends Payeur implements Path<PayeurRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PayeurPath(Table<O> path, ForeignKey<O, PayeurRecord> childPath, InverseForeignKey<O, PayeurRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PayeurPath(Name alias, Table<PayeurRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PayeurPath as(String alias) {
            return new PayeurPath(DSL.name(alias), this);
        }

        @Override
        public PayeurPath as(Name alias) {
            return new PayeurPath(alias, this);
        }

        @Override
        public PayeurPath as(Table<?> alias) {
            return new PayeurPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Core.CORE;
    }

    @Override
    public Identity<PayeurRecord, Long> getIdentity() {
        return (Identity<PayeurRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PayeurRecord> getPrimaryKey() {
        return Keys.PAYEUR_PKEY;
    }

    @Override
    public List<UniqueKey<PayeurRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PAYEUR_IDENTIFIANT_KEY);
    }

    private transient FluxPath _flux;

    /**
     * Get the implicit to-many join path to the <code>core.flux</code> table
     */
    public FluxPath flux() {
        if (_flux == null)
            _flux = new FluxPath(this, null, Keys.FLUX__FLUX_PAYEUR_ID_FKEY.getInverseKey());

        return _flux;
    }

    @Override
    public List<Check<PayeurRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("payeur_type_ck"), "((type = ANY (ARRAY['ETAT'::text, 'OPERATEUR'::text, 'COLLECTIVITE'::text, 'HOPITAL'::text, 'UE'::text, 'AUTRE'::text])))", true)
        );
    }

    @Override
    public Payeur as(String alias) {
        return new Payeur(DSL.name(alias), this);
    }

    @Override
    public Payeur as(Name alias) {
        return new Payeur(alias, this);
    }

    @Override
    public Payeur as(Table<?> alias) {
        return new Payeur(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Payeur rename(String name) {
        return new Payeur(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Payeur rename(Name name) {
        return new Payeur(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Payeur rename(Table<?> name) {
        return new Payeur(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payeur where(Condition condition) {
        return new Payeur(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payeur where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payeur where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payeur where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payeur where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payeur where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payeur where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payeur where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payeur whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payeur whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
