/*
 * This file is generated by jOOQ.
 */
package fr.suivons.db.jooq;


import fr.suivons.db.jooq.core.Core;
import fr.suivons.db.jooq.ops.Ops;
import fr.suivons.db.jooq.raw.Raw;

import java.util.Arrays;
import java.util.List;

import org.jooq.Constants;
import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * Modèle normalisé : entreprises, payeurs, flux
     */
    public final Core CORE = Core.CORE;

    /**
     * Exploitation : sources, exécutions, rejets, signalements
     */
    public final Ops OPS = Ops.OPS;

    /**
     * Données brutes telles que reçues, rejouables
     */
    public final Raw RAW = Raw.RAW;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.asList(
            Core.CORE,
            Ops.OPS,
            Raw.RAW
        );
    }

    /**
     * A reference to the 3.21 minor release of the code generator. If this
     * doesn't compile, it's because the runtime library uses an older minor
     * release, namely: 3.21. You can turn off the generation of this reference
     * by specifying /configuration/generator/generate/jooqVersionReference
     */
    private static final String REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_21;
}
